# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: cd weather_app/src/weather 
  displayName: ' Move to setup.py '

steps:
- script: python setup.py sdist 
  displayName: 'Make a targz file '


steps:
- script: 'pip install weather.targz -i https://pypi/simple' 
  displayName: 'Installation of python package for weather app'

